pull_request_rules:
  - actions:
      merge:
        strict: smart+fasttrack
        method: squash
    name: Automatically merge pull requests
    conditions:
      - label=merge me
      - '#approved-reviews-by>=1'
