queue_rules:
  - name: default
    # Mergify always respects the branch protection settings
    # so we can left empty mergify own ones
    conditions: []

pull_request_rules:
  - name: Automatically merge pull requests
    conditions:
      - label=merge me
      - '#approved-reviews-by>=1'
    actions:
      queue:
        method: squash
        name: default
