queue_rules:
  - name: default

pull_request_rules:
    name: Automatically merge pull requests
    conditions:
      - label=merge me
      - '#approved-reviews-by>=1'
    actions:
      queue:
        method: squash
        name: default
