queue_rules:
  - name: default
    # Mergify always respects the branch protection settings
    # so we can left empty mergify own ones
    queue_conditions:
      - label=merge me
      - '#approved-reviews-by>=1'
    merge_conditions: []
    merge_method: squash

pull_request_rules:
  - name: Automatically update pull requests
    conditions:
      - label=merge me
    actions:
      update:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
