# release CI for FreeBSD
compute_engine_instance:
  image_project: freebsd-org-cloud-dev
  image: family/freebsd-13-1
  platform: freebsd
  disk: 100 # Gb

build_task:
  timeout_in: 120m
  only_if: $CIRRUS_TAG != ''
  env:
    AWS_ACCESS_KEY_ID: ENCRYPTED[dc5896620ebc12e98e6bbe96f72c5a2fe3785f439b7b2346797355f8d329a4bfd8ef6e58086bfc014be0d914424101cd]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[6501cd594aca08c6c67cc679dd6f6d30db0cd44a81cceddebf32bb3d0a37f9af19cd71ddb7169d3f7b284a7829969f9e]
    S3_HOST: ENCRYPTED[d3fef1b5850e85d80dd1684370b53183df2218f2d36509108a2703371afd9ebd3f9596ad4de52487c15ea29baed606b7]
    TARBALL_EXT: "tar.xz"
    ARCH: 64
    ARTIFACT: "x86_64-freebsd"
    DISTRO: "na"
    RUNNER_OS: "FreeBSD"
    ADD_CABAL_ARGS: "--enable-split-sections"
    GITHUB_WORKSPACE: ${CIRRUS_WORKING_DIR}
    CABAL_CACHE_NONFATAL: "yes"
  matrix:
    - name: build-ghc-8.10.7
      env:
        GHC_VERSION: 8.10.7
    - name: build-ghc-9.0.2
      env:
        GHC_VERSION: 9.0.2
    - name: build-ghc-9.2.5
      env:
        GHC_VERSION: 9.2.5
  install_script: pkg install -y hs-cabal-install git bash misc/compat10x misc/compat11x misc/compat12x gmake patchelf tree
  script:
    - tzsetup Etc/GMT
    - adjkerntz -a
    - bash .github/scripts/build.sh
    - tar caf out.tar.xz out/ store/
  binaries_artifacts:
    path: "out.tar.xz"


bindist_task:
  name: bindist
  depends_on:
    - build-ghc-8.10.7
    - build-ghc-9.0.2
    - build-ghc-9.2.5
  timeout_in: 120m
  only_if: $CIRRUS_TAG != ''
  env:
    TARBALL_EXT: "tar.xz"
    ARCH: 64
    ARTIFACT: "x86_64-freebsd"
    DISTRO: "na"
    RUNNER_OS: "FreeBSD"
    GITHUB_WORKSPACE: ${CIRRUS_WORKING_DIR}
  install_script: pkg install -y hs-cabal-install git bash misc/compat10x misc/compat11x misc/compat12x gmake patchelf tree unzip
  script:
    - tzsetup Etc/GMT
    - adjkerntz -a

    - curl -o binaries-8.10.7.tar.xz -L https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/build-ghc-8.10.7/binaries/out.tar.xz
    - tar xvf binaries-8.10.7.tar.xz
    - rm -f binaries-8.10.7.tar.xz

    - curl -o binaries-9.0.2.tar.xz -L https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/build-ghc-9.0.2/binaries/out.tar.xz
    - tar xvf binaries-9.0.2.tar.xz
    - rm -f binaries-9.0.2.tar.xz

    - curl -o binaries-9.2.5.tar.xz -L https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/build-ghc-9.2.5/binaries/out.tar.xz
    - tar xvf binaries-9.2.5.tar.xz
    - rm -f binaries-9.2.5.tar.xz

    - bash .github/scripts/bindist.sh
  bindist_artifacts:
    path: "./out/*.tar.xz"

test_task:
  name: test
  depends_on:
    - bindist
  timeout_in: 120m
  only_if: $CIRRUS_TAG != ''
  env:
    TARBALL_EXT: "tar.xz"
    ARCH: 64
    ARTIFACT: "x86_64-freebsd"
    DISTRO: "na"
    RUNNER_OS: "FreeBSD"
    GITHUB_WORKSPACE: ${CIRRUS_WORKING_DIR}
  install_script: pkg install -y hs-cabal-install git bash misc/compat10x misc/compat11x misc/compat12x gmake patchelf tree unzip
  script:
    - tzsetup Etc/GMT
    - adjkerntz -a

    - curl -O -L https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/bindist/bindist.zip
    - unzip bindist.zip

    - bash .github/scripts/test.sh

