# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      export GHCUP_INSTALL_BASE_PREFIX=/workspace
      export BOOTSTRAP_HASKELL_NONINTERACTIVE=1
      export BOOTSTRAP_HASKELL_MINIMAL=1
      export CABAL_DIR=/workspace/.cabal
      export STACK_ROOT=/workspace/.stack
      curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

      # ensure that there is an HLS binary for the installed GHC version
      /workspace/.ghcup/bin/ghcup install ghc 8.10.6 --set
      /workspace/.ghcup/bin/ghcup install cabal

      # Add ghcup binaries to the PATH since VSCode does not see 'source .ghcup/env'
      pushd /usr/local/bin
      sudo ln -s /workspace/.ghcup/bin/* /usr/local/bin
      popd

      # Fix the default Cabal config since VSCode does not see CABAL_DIR 
      cabal update
      mkdir ~/.cabal
      cp /workspace/.cabal/config ~/.cabal/config
    init: | 
      cabal build --enable-tests      
    command: | 
      cabal build --enable-tests

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports: []

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - "haskell.haskell"
    - "justusadam.language-haskell"
    - "usernamehw.errorlens"