resolver: nightly-2022-08-15

packages:
- .
- ./hie-compat
- ./hls-graph
- ./ghcide/
- ./ghcide/test
- ./hls-plugin-api
- ./hls-test-utils
- ./shake-bench
- ./plugins/hls-call-hierarchy-plugin
- ./plugins/hls-class-plugin
# - ./plugins/hls-haddock-comments-plugin
- ./plugins/hls-eval-plugin
- ./plugins/hls-explicit-imports-plugin
- ./plugins/hls-qualify-imported-names-plugin
- ./plugins/hls-refine-imports-plugin
- ./plugins/hls-hlint-plugin
- ./plugins/hls-rename-plugin
# - ./plugins/hls-retrie-plugin
# - ./plugins/hls-splice-plugin
# - ./plugins/hls-tactics-plugin
# - ./plugins/hls-brittany-plugin
- ./plugins/hls-stylish-haskell-plugin
- ./plugins/hls-floskell-plugin
- ./plugins/hls-fourmolu-plugin
- ./plugins/hls-pragmas-plugin
- ./plugins/hls-module-name-plugin
- ./plugins/hls-ormolu-plugin
- ./plugins/hls-alternate-number-format-plugin
- ./plugins/hls-code-range-plugin
- ./plugins/hls-change-type-signature-plugin
- ./plugins/hls-gadt-plugin
- ./plugins/hls-explicit-fixity-plugin
- ./plugins/hls-refactor-plugin

extra-deps:
- floskell-0.10.6@sha256:e77d194189e8540abe2ace2c7cb8efafc747ca35881a2fefcbd2d40a1292e036,3819
- heapsize-0.3.0.1@sha256:0b69aa97a46d819b700ac7b145f3b5493c3565cf2c5b8298682238d405d0326e,1417
- hiedb-0.4.1.0@sha256:fb20c657d9ecc91701b00dffcf4bbd77cb83720a1f9d867badd77ea227973135,2875
- implicit-hie-0.1.2.7@sha256:82bbbb1a8c05f99c8af3c16ac53e80c8648d8bf047b25ed5ce45a135bd736907,3122
- implicit-hie-cradle-0.5.0.0@sha256:4276f60f3a59bc22df03fd918f73bca9f777de9568f85e3a8be8bd7566234a59,2368
- git: git@github.com:haskell/lsp
  commit: b0f8596887088b8ab65fc1015c773f45b47234ae
  subdirs:
  - lsp
  - lsp-types
  - lsp-test
- monad-dijkstra-0.1.1.3@sha256:d2fc098d7c122555e726830a12ae0423ac187f89de9228f32e56e2f6fc2238e1,1900
- retrie-1.2.0.1
- co-log-core-0.3.1.0

# currently needed for ghcide>extra, etc.
allow-newer: true

ghc-options:
  "$everything": -haddock

configure-options:
  ghcide:
    - --disable-library-for-ghci
  haskell-language-server:
    - --disable-library-for-ghci
  heapsize:
    - --disable-library-for-ghci

flags:
  haskell-language-server:
    pedantic: true

    ignore-plugins-ghc-bounds: true
    brittany: false
    haddockComments: false
    retrie: false
    splice: false
    tactic: false

  retrie:
    BuildExecutable: false
  # Stack doesn't support automatic flags.
  # Use ghc-lib force instead of ghc itself
  ghc-lib-parser-ex:
    auto: false
  hlint:
    ghc-lib: true
  stylish-haskell:
    ghc-lib: true
  hyphenation:
    embed: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false

system-ghc: true
