resolver: nightly-2024-06-12 # ghc-9.8.2

packages:
  - .
  - ./hie-compat
  - ./hls-graph
  - ./ghcide/
  - ./hls-plugin-api
  - ./hls-test-utils
  # - ./shake-bench

ghc-options:
  "$everything": -haddock

allow-newer: true
allow-newer-deps:
  - extensions
  - hw-fingertree
  - retrie

extra-deps:
  - floskell-0.11.1
  - hiedb-0.6.0.1
  - hie-bios-0.14.0
  - implicit-hie-0.1.4.0
  - hw-fingertree-0.1.2.1
  - lsp-2.7.0.0
  - lsp-test-0.17.1.0
  - lsp-types-2.3.0.0
  - monad-dijkstra-0.1.1.5
  - stylish-haskell-0.14.6.0
  - retrie-1.2.3

  # stan dependencies not found in the stackage snapshot
  - stan-0.1.3.0
  - dir-traverse-0.2.3.0
  - extensions-0.1.0.1
  - trial-0.0.0.0
  - trial-optparse-applicative-0.0.0.0
  - trial-tomland-0.0.0.0
  - cabal-add-0.1
  - cabal-install-parsers-0.6.1.1

configure-options:
  ghcide:
    - --disable-library-for-ghci
  haskell-language-server:
    - --disable-library-for-ghci

flags:
  haskell-language-server:
    pedantic: true
  stylish-haskell:
    ghc-lib: true
  retrie:
    BuildExecutable: false
  cabal-add:
    cabal-syntax: true

nix:
  packages: [icu libcxx zlib]

concurrent-tests: false
