resolver: nightly-2023-07-10 # ghc-9.6.2

packages:
  - .
  - ./hie-compat
  - ./hls-graph
  - ./ghcide/
  - ./ghcide/test
  - ./hls-plugin-api
  - ./hls-test-utils
  # - ./shake-bench
  - ./plugins/hls-alternate-number-format-plugin
  - ./plugins/hls-cabal-fmt-plugin
  - ./plugins/hls-cabal-plugin
  - ./plugins/hls-call-hierarchy-plugin
  - ./plugins/hls-change-type-signature-plugin
  - ./plugins/hls-class-plugin
  - ./plugins/hls-code-range-plugin
  - ./plugins/hls-eval-plugin
  - ./plugins/hls-explicit-fixity-plugin
  - ./plugins/hls-explicit-imports-plugin
  - ./plugins/hls-explicit-record-fields-plugin
  # - ./plugins/hls-floskell-plugin
  - ./plugins/hls-fourmolu-plugin
  - ./plugins/hls-gadt-plugin
  - ./plugins/hls-hlint-plugin
  - ./plugins/hls-module-name-plugin
  - ./plugins/hls-ormolu-plugin
  - ./plugins/hls-overloaded-record-dot-plugin
  - ./plugins/hls-pragmas-plugin
  - ./plugins/hls-qualify-imported-names-plugin
  - ./plugins/hls-refactor-plugin
  - ./plugins/hls-rename-plugin
  - ./plugins/hls-retrie-plugin
  - ./plugins/hls-splice-plugin
  - ./plugins/hls-stylish-haskell-plugin

ghc-options:
  "$everything": -haddock

allow-newer: true

extra-deps:
- Cabal-syntax-3.10.1.0@sha256:bb835ebab577fd0f9c11dab96210dbb8d68ffc62652576f4b092563c345930e7,7434
# - floskell-0.10.7
- hiedb-0.4.3.0
- implicit-hie-0.1.2.7
- implicit-hie-cradle-0.5.0.1
- fourmolu-0.12.0.0
- algebraic-graphs-0.6.1
- retrie-1.2.2
- hw-fingertree-0.1.2.1
- hw-prim-0.6.3.2
- ansi-terminal-0.11.5
- lsp-2.2.0.0
- lsp-test-0.16.0.0
- lsp-types-2.0.2.0


configure-options:
  ghcide:
      - --disable-library-for-ghci
  haskell-language-server:
      - --disable-library-for-ghci

flags:
  haskell-language-server:
    pedantic: true
  retrie:
    BuildExecutable: false
  # Stack doesn't support automatic flags.
  hyphenation:
    embed: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
