resolver: lts-23.18 # ghc-9.8.4

packages:
  - .
  - ./hie-compat
  - ./hls-graph
  - ./ghcide/
  - ./hls-plugin-api
  - ./hls-test-utils
  # - ./shake-bench

ghc-options:
  "$everything": -haddock

allow-newer: true
allow-newer-deps:
  - extensions
  - hw-fingertree
  - retrie
  # stan dependencies
  - directory-ospath-streaming

extra-deps:
  - floskell-0.11.1
  - hiedb-0.6.0.2
  - implicit-hie-0.1.4.0
  - hie-bios-0.15.0
  - hw-fingertree-0.1.2.1
  - monad-dijkstra-0.1.1.5
  - retrie-1.2.3

  # stan dependencies not found in the stackage snapshot
  - stan-0.2.1.0
  - dir-traverse-0.2.3.0
  - extensions-0.1.0.1
  - trial-0.0.0.0
  - trial-optparse-applicative-0.0.0.0
  - trial-tomland-0.0.0.0
  - directory-ospath-streaming-0.2.2

configure-options:
  ghcide:
    - --disable-library-for-ghci
  haskell-language-server:
    - --disable-library-for-ghci

flags:
  haskell-language-server:
    pedantic: true
  stylish-haskell:
    ghc-lib: true
  retrie:
    BuildExecutable: false
  cabal-add:
    cabal-syntax: true
  # stan dependencies
  directory-ospath-streaming:
      os-string: false

nix:
  packages: [icu libcxx zlib]

concurrent-tests: false
