resolver: nightly-2023-07-10 # ghc-9.6.2

packages:
  - .
  - ./hie-compat
  - ./hls-graph
  - ./ghcide/
  - ./ghcide/test
  - ./hls-plugin-api
  - ./hls-test-utils
  # - ./shake-bench
  - ./plugins/hls-alternate-number-format-plugin
  - ./plugins/hls-cabal-fmt-plugin
  - ./plugins/hls-cabal-plugin
  - ./plugins/hls-call-hierarchy-plugin
  - ./plugins/hls-change-type-signature-plugin
  - ./plugins/hls-class-plugin
  - ./plugins/hls-code-range-plugin
  - ./plugins/hls-eval-plugin
  - ./plugins/hls-explicit-fixity-plugin
  - ./plugins/hls-explicit-imports-plugin
  - ./plugins/hls-explicit-record-fields-plugin
  - ./plugins/hls-floskell-plugin
  - ./plugins/hls-fourmolu-plugin
  - ./plugins/hls-gadt-plugin
  - ./plugins/hls-hlint-plugin
  - ./plugins/hls-module-name-plugin
  - ./plugins/hls-ormolu-plugin
  - ./plugins/hls-overloaded-record-dot-plugin
  - ./plugins/hls-pragmas-plugin
  - ./plugins/hls-qualify-imported-names-plugin
  - ./plugins/hls-refactor-plugin
  - ./plugins/hls-rename-plugin
  - ./plugins/hls-retrie-plugin
  - ./plugins/hls-splice-plugin
  - ./plugins/hls-stan-plugin
  - ./plugins/hls-stylish-haskell-plugin
  - ./plugins/hls-semantic-tokens-plugin

ghc-options:
  "$everything": -haddock

allow-newer: true

extra-deps:
- floskell-0.11.1
- retrie-1.2.2
- hiedb-0.5.0.1
- implicit-hie-0.1.4.0
- hie-bios-0.13.1
- lsp-2.3.0.0
- lsp-test-0.16.0.1
- lsp-types-2.1.0.0
- attoparsec-aeson-2.1.0.0
- hw-fingertree-0.1.2.1
- integer-conversion-0.1.0.1
- monad-dijkstra-0.1.1.4
- hw-prim-0.6.3.2
- optparse-applicative-0.17.1.0

# stan and friends
- stan-0.1.2.0
- clay-0.14.0
- colourista-0.1.0.2
- dir-traverse-0.2.3.0
- extensions-0.1.0.1
- relude-1.2.1.0
- slist-0.2.1.0
- tomland-1.3.3.2
- trial-0.0.0.0
- trial-optparse-applicative-0.0.0.0
- trial-tomland-0.0.0.0
- validation-selective-0.2.0.0

configure-options:
  ghcide:
      - --disable-library-for-ghci
  haskell-language-server:
      - --disable-library-for-ghci

flags:
  haskell-language-server:
    pedantic: true
  retrie:
    BuildExecutable: false

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
