name: ghc-lib

on: [pull_request]
jobs:
  nix:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['ghc8102']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.03
    - uses: cachix/cachix-action@v8
      with:
        name: haskell-language-server
        authToken: '${{ secrets.HLS_CACHIX_AUTH_TOKEN }}'

    - name: ghc-lib
      run: |
        echo "package ghcide" >> cabal.project.local
        echo "  flags: ghc-lib" >> cabal.project.local
        echo "package hie-compat" >> cabal.project.local
        echo "  flags: ghc-lib" >> cabal.project.local

    - name: Build ghcide
      run: nix-shell --argstr compiler ${{ matrix.ghc }} --run "cabal update && cabal build ghcide"
