name: Cache eviction

on:
  workflow_dispatch:
    inputs:
      key:
        description: Which cache to evict
        required: true
        default: '/'
        type: choice
        options:
        - aarch64-apple-darwin
        - aarch64-linux-ubuntu20
        - x86_64-apple-darwin
        - x86_64-freebsd
        - x86_64-linux-centos7
        - x86_64-linux-deb10
        - x86_64-linux-deb11
        - x86_64-linux-deb9
        - x86_64-linux-fedora27
        - x86_64-linux-fedora33
        - x86_64-linux-mint19.3
        - x86_64-linux-mint20.2
        - x86_64-linux-ubuntu18.04
        - x86_64-linux-ubuntu20.04
        - x86_64-linux-ubuntu22.04
        - /
jobs:
  evict:
    runs-on: ubuntu-latest

    steps:
    - name: Remove from S3
      uses: vitorsgomes/s3-rm-action@master
      with:
        args: --recursive
      env:
        AWS_S3_ENDPOINT: https://${{ secrets.S3_HOST }}
        AWS_S3_BUCKET: haskell-language-server
        AWS_REGION: us-west-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PATH_TO_DELETE: ${{ github.event.inputs.key }}
